# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 21:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('decision_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('origin_user_id', models.CharField(max_length=128)),
                ('target_user_id', models.CharField(max_length=128)),
                ('origin_user_choice', models.BooleanField(default=None)),
                ('target_user_choice', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_id_1', models.CharField(max_length=128)),
                ('user_id_2', models.CharField(max_length=128)),
                ('date_time', models.DateField()),
                ('message_count', models.IntegerField()),
                ('last_message', models.CharField(max_length=512)),
                ('last_seen_user_1', models.IntegerField()),
                ('last_seen_user_2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sender_id', models.CharField(max_length=128)),
                ('message_number', models.IntegerField()),
                ('date_time', models.DateField()),
                ('message_body', models.CharField(max_length=512)),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gingr_server.Match')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2017, 11, 13, 21, 8, 46, 288182))),
                ('last_login', models.DateTimeField()),
                ('first_name', models.CharField(max_length=256, unique=True)),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=32)),
                ('hair', models.CharField(max_length=32)),
                ('bio', models.CharField(max_length=256)),
                ('photo', models.ImageField(upload_to='profile-photos/%s')),
                ('latitude', models.DecimalField(decimal_places=6, default=None, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=None, max_digits=9)),
                ('min_age', models.IntegerField(default=18)),
                ('max_age', models.IntegerField(default=100)),
                ('max_distance', models.IntegerField(default=100)),
                ('ginger_pref', models.CharField(max_length=32)),
                ('gender_pref', models.CharField(max_length=32)),
                ('profile_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
