# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 21:15
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gingr_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2017, 11, 13, 21, 15, 6, 109254))),
                ('last_login', models.DateTimeField()),
                ('DOB', models.DateField()),
                ('gender', models.CharField(max_length=32)),
                ('hair', models.CharField(max_length=32)),
                ('bio', models.CharField(max_length=256)),
                ('photo', models.ImageField(upload_to='profile-photos/%s')),
                ('latitude', models.DecimalField(decimal_places=6, default=None, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=None, max_digits=9)),
                ('min_age', models.IntegerField(default=18)),
                ('max_age', models.IntegerField(default=100)),
                ('max_distance', models.IntegerField(default=100)),
                ('ginger_pref', models.CharField(max_length=32)),
                ('gender_pref', models.CharField(max_length=32)),
                ('profile_complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
