# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gingr_server', '0011_auto_20171113_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='first_name',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender_pref',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ginger_pref',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='hair',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
