# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gingr_server', '0012_auto_20171114_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_name',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
