# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gingr_server', '0013_userinfo_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='ginger_pref',
            new_name='hair_pref',
        ),
    ]
