# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gingr_server', '0014_auto_20171114_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='DOB',
            new_name='dob',
        ),
    ]
