# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gingr_server', '0017_auto_20171114_2036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UserProfile',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
